---
kind: pipeline
name: windows-1803

platform:
  os: windows
  arch: amd64
  version: 1803

steps:
- name: build-push
  pull: always
  image: golang:1.11
  commands:
  - "go build -v -ldflags \"-X main.build=${DRONE_BUILD_NUMBER}\" -a -o release/windows/amd64/drone-ansible"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go
  when:
    event:
    - push
    - pull_request

- name: build-tag
  pull: always
  image: golang:1.11
  commands:
  - "go build -v -ldflags \"-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}\" -a -o release/windows/amd64/drone-ansible"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go
  when:
    event:
    - tag

- name: executable
  pull: always
  image: golang:1.11
  commands:
  - ./release/windows/amd64/drone-ansible --help

- name: dryrun
  pull: always
  image: plugins/docker:windows-1803
  settings:
    dockerfile: docker/Dockerfile.windows.1803
    dry_run: true
    password:
      from_secret: docker_password
    repo: plugins/ansible
    tags: windows-1803
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: //./pipe/docker_engine
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:windows-1803
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1803
    dockerfile: docker/Dockerfile.windows.1803
    password:
      from_secret: docker_password
    repo: plugins/ansible
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: //./pipe/docker_engine
  when:
    event:
    - push
    - tag

volumes:
- name: gopath
  temp:
- name: docker_pipe
  host:
    path: //./pipe/docker_engine

trigger:
  branch:
  - master

depends_on:
- testing

---
kind: pipeline
name: windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: build-push
  pull: always
  image: golang:1.11
  commands:
  - "go build -v -ldflags \"-X main.build=${DRONE_BUILD_NUMBER}\" -a -o release/windows/amd64/drone-ansible"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go
  when:
    event:
    - push
    - pull_request

- name: build-tag
  pull: always
  image: golang:1.11
  commands:
  - "go build -v -ldflags \"-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}\" -a -o release/windows/amd64/drone-ansible"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go
  when:
    event:
    - tag

- name: executable
  pull: always
  image: golang:1.11
  commands:
  - ./release/windows/amd64/drone-ansible --help

- name: dryrun
  pull: always
  image: plugins/docker:windows-1809
  settings:
    dockerfile: docker/Dockerfile.windows.1809
    dry_run: true
    password:
      from_secret: docker_password
    repo: plugins/ansible
    tags: windows-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: //./pipe/docker_engine
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:windows-1809
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1809
    dockerfile: docker/Dockerfile.windows.1809
    password:
      from_secret: docker_password
    repo: plugins/ansible
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: //./pipe/docker_engine
  when:
    event:
    - push
    - tag

volumes:
- name: gopath
  temp:
- name: docker_pipe
  host:
    path: //./pipe/docker_engine

trigger:
  branch:
  - master

depends_on:
- testing

---
kind: pipeline
name: notifications

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: manifest
  pull: always
  image: plugins/manifest:1
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username

- name: microbadger
  pull: always
  image: plugins/webhook:1
  settings:
    url:
      from_secret: microbadger_url

trigger:
  event:
  - push
  - tag

depends_on:
- windows-1803
- windows-1809

...
