# escape=`
FROM plugins/base:windows-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Ansible" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

# TODO: install required tools

ADD release\drone-ansible.exe c:\drone-ansible.exe
ENTRYPOINT [ "c:\\drone-ansible.exe" ]
